version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    environment: [POSTGRES_HOST_AUTH_METHOD=trust]
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

  backend:
    build: ./app/
    env_file: .env
    depends_on:
       - db
    ports:
      - 8000:8000
    restart: on-failure

  frontend:
    build: ./frontend/
    env_file: .env
    ports:
      - 7070:7070
    restart: on-failure
